# Generated by Django 6.0 on 2025-12-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='todoList',
            new_name='todolist',
        ),
    ]
